/*
 * Copyright MalchroSoft - Aymeric MALCHROWICZ. All right reserved.
 * The source code that contains this comment is an intellectual property
 * of MalchroSoft [Aymeric MALCHROWICZ]. Use is subject to licence terms.
 */

/*
 * LicenseActivationDialog.java
 *
 * Created on 28 juin 2011, 23:35:17
 */
package com.malchrosoft.ihm.dialog.security;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Aymeric Malchrowicz
 */
public class LicenseActivationDialog extends javax.swing.JDialog
{
	private boolean autoEmailCorrection = true;

	/** Creates new form LicenseActivationDialog */
	public LicenseActivationDialog()
	{
		initComponents();
		this.getCancelButton().addActionListener(new ActionListener()
		{
			@Override
			public void actionPerformed(ActionEvent e)
			{
				LicenseActivationDialog.this.setVisible(false);
			}
		});
		this.getEmailTextField().addKeyListener(new KeyAdapter()
		{
			@Override
			public void keyReleased(KeyEvent e)
			{
				if (!autoEmailCorrection) return;
				int position = LicenseActivationDialog.this.getEmailTextField().getCaretPosition();
				String email = LicenseActivationDialog.this.getEmailTextField().getText();
				String invalid = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890-._@";
				boolean changed = false;
//				if (!invalid.contains(e.getKeyChar() + ""))
//				{
//					LicenseActivationDialog.this.getEmailTextField().setText(email.substring(0, email.length() - 1));
//				}
				for (int i = email.length() - 1; i >= 0; i--)
				{
					if (!invalid.contains(email.charAt(i) + ""))
					{
						email = (i > 0 ? email.substring(0, i) : "") + email.substring(i + 1);
						changed = true;
					}
				}
				if (changed)
				{
					LicenseActivationDialog.this.getEmailTextField().setText(email);
					if (position < email.length()) LicenseActivationDialog.this.getEmailTextField().
							setCaretPosition(
							position - 1);
				}
			}
		});
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        commentLabelScroll = new javax.swing.JScrollPane();
        commentLabel = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        emailLabel = new javax.swing.JLabel();
        emailExampleLabel = new javax.swing.JLabel();
        emailPanel = new javax.swing.JPanel();
        emailTextField = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        licenseLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        licenseNumberPanel = new javax.swing.JPanel();
        licenseTextField = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        activationTextArea = new javax.swing.JTextArea();
        buttonsPanel = new javax.swing.JPanel();
        validationButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setTitle("Licence");
        setResizable(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(6, 6, 6, 6));
        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        commentLabelScroll.setBorder(null);

        commentLabel.setColumns(20);
        commentLabel.setEditable(false);
        commentLabel.setFont(new java.awt.Font("Tahoma", 0, 11));
        commentLabel.setLineWrap(true);
        commentLabel.setRows(3);
        commentLabel.setText("Comment label content...");
        commentLabel.setWrapStyleWord(true);
        commentLabel.setDoubleBuffered(true);
        commentLabel.setFocusable(false);
        commentLabel.setOpaque(false);
        commentLabelScroll.setViewportView(commentLabel);

        jPanel2.add(commentLabelScroll);

        getContentPane().add(jPanel2);

        jPanel3.setMinimumSize(new java.awt.Dimension(450, 50));
        jPanel3.setPreferredSize(new java.awt.Dimension(450, 60));
        jPanel3.setLayout(new java.awt.BorderLayout());

        emailLabel.setText("Numéro de licence : ");
        emailLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(6, 6, 6, 1));
        jPanel3.add(emailLabel, java.awt.BorderLayout.WEST);

        emailExampleLabel.setForeground(new java.awt.Color(102, 102, 102));
        emailExampleLabel.setText("ex : toto@fai.com");
        emailExampleLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 120, 10, 6));
        jPanel3.add(emailExampleLabel, java.awt.BorderLayout.SOUTH);

        emailPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(6, 6, 6, 6));
        emailPanel.setLayout(new javax.swing.BoxLayout(emailPanel, javax.swing.BoxLayout.Y_AXIS));

        emailTextField.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), javax.swing.BorderFactory.createEmptyBorder(3, 6, 3, 6)));
        emailTextField.setMargin(new java.awt.Insets(2, 6, 2, 6));
        emailPanel.add(emailTextField);

        jPanel3.add(emailPanel, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel3);

        jPanel1.setMinimumSize(new java.awt.Dimension(450, 50));
        jPanel1.setPreferredSize(new java.awt.Dimension(450, 60));
        jPanel1.setLayout(new java.awt.BorderLayout());

        licenseLabel.setText("Numéro de licence : ");
        licenseLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(6, 6, 6, 1));
        jPanel1.add(licenseLabel, java.awt.BorderLayout.WEST);

        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("ex : 1S2R-45ef-7GHT-65E3");
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 120, 10, 6));
        jPanel1.add(jLabel1, java.awt.BorderLayout.SOUTH);

        licenseNumberPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(6, 6, 6, 6));
        licenseNumberPanel.setLayout(new javax.swing.BoxLayout(licenseNumberPanel, javax.swing.BoxLayout.Y_AXIS));

        licenseTextField.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), javax.swing.BorderFactory.createEmptyBorder(3, 6, 3, 6)));
        licenseTextField.setMargin(new java.awt.Insets(2, 6, 2, 6));
        licenseNumberPanel.add(licenseTextField);

        jPanel1.add(licenseNumberPanel, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1);

        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 6, 1, 6));
        jPanel4.setPreferredSize(new java.awt.Dimension(450, 100));
        jPanel4.setLayout(new java.awt.BorderLayout());

        activationTextArea.setColumns(20);
        activationTextArea.setLineWrap(true);
        activationTextArea.setRows(5);
        activationTextArea.setWrapStyleWord(true);
        jScrollPane1.setViewportView(activationTextArea);

        jPanel4.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel4);

        buttonsPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(6, 1, 6, 1));
        buttonsPanel.setLayout(new javax.swing.BoxLayout(buttonsPanel, javax.swing.BoxLayout.LINE_AXIS));

        validationButton.setText("Activer");
        buttonsPanel.add(validationButton);

        cancelButton.setText("Annuler");
        buttonsPanel.add(cancelButton);

        getContentPane().add(buttonsPanel);

        pack();
    }// </editor-fold>//GEN-END:initComponents

	public JTextArea getActivationTextArea()
	{
		return activationTextArea;
	}

	public final JButton getCancelButton()
	{
		return cancelButton;
	}

	public JLabel getLicenseLabel()
	{
		return licenseLabel;
	}

	public JPanel getLicenseNumberPanel()
	{
		return licenseNumberPanel;
	}

	public JTextField getLicenseTextField()
	{
		return licenseTextField;
	}

	public JButton getValidationButton()
	{
		return validationButton;
	}

	public JTextArea getCommentLabel()
	{
		return commentLabel;
	}

	public JLabel getEmailLabel()
	{
		return emailLabel;
	}

	public final JTextField getEmailTextField()
	{
		return emailTextField;
	}

	public boolean isAutoEmailCorrection()
	{
		return autoEmailCorrection;
	}

	public void setAutoEmailCorrection(boolean autoEmailCorrection)
	{
		this.autoEmailCorrection = autoEmailCorrection;
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[])
	{
		java.awt.EventQueue.invokeLater(new Runnable()
		{
			public void run()
			{
				LicenseActivationDialog d = new LicenseActivationDialog();
				d.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
				d.getCancelButton().addActionListener(new ActionListener()
				{
					@Override
					public void actionPerformed(ActionEvent e)
					{
						System.exit(0);
					}
				});
				d.setVisible(true);
			}
		});
	}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea activationTextArea;
    private javax.swing.JPanel buttonsPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextArea commentLabel;
    private javax.swing.JScrollPane commentLabelScroll;
    private javax.swing.JLabel emailExampleLabel;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JPanel emailPanel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel licenseLabel;
    private javax.swing.JPanel licenseNumberPanel;
    private javax.swing.JTextField licenseTextField;
    private javax.swing.JButton validationButton;
    // End of variables declaration//GEN-END:variables
}
