/*
 * FenetreAPropos.java
 *
 * Created on 10 avril 2007, 01:40
 */

package com.malchrosoft.ihm;

import com.malchrosoft.graphics.GraphicThemeUtilities;
import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JTextPane;
import org.jdesktop.swingx.JXFrame;
import org.jdesktop.swingx.painter.CompoundPainter;
import org.jdesktop.swingx.painter.TextPainter;

/**
 *
 * @author  Aymeric
 */
public class FenetreAPropos extends JXFrame
{
    
    /** 
     * Creer une nouvelle fenetre A propos
     * @param applicationName Le nom de l'application
     * @param applicationVersion Le version de l'application
     * @param applicationDescription La description de l'application
     * @param applicationAuthors La liste des auteurs de l'application
     */
    public FenetreAPropos(String applicationName, String applicationVersion,
        String applicationDescription, String applicationAuthors)
    {
        this.initComponents();
        this.setTitle("A propos de " + applicationName);
        //this.lbApplicationName.setText(applicationName);
        this.lbApplicationVersion.setText(applicationVersion);
        this.textPaneDescription.setText(applicationDescription);
        this.textPaneAuthor.setText(applicationAuthors);
        
        /*this.imagePainterLogo = GraphicThemeUtilities
            .buildGlowImagePainter("/commun/images/Logo1.PNG", 0, 0);*/
         
        this.panelCentral.setBorder(GraphicThemeUtilities.getNeonBorder());
        
        // Text du nom de l'application
        TextPainter applicationNameText = GraphicThemeUtilities
            .buildGlowTextPainter(applicationName, 190, 20, Color.WHITE, 
            this.lbApplicationName.getFont());
        this.lbApplicationName.setText(" ");
        // Text de la version de l'application
        TextPainter applicationVersionText = GraphicThemeUtilities
            .buildGlowTextPainter(applicationVersion, 190, 45, Color.WHITE, 
            this.lbApplicationVersion.getFont());
        this.lbApplicationVersion.setText(" ");
        
        this.panelCentral.setBackgroundPainter(new CompoundPainter(
            GraphicThemeUtilities
            .getBlackGlossStripeBackgroundPainter(0, 200), 
            applicationNameText, applicationVersionText, this.imagePainterLogo)); 
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imagePainterLogo = new org.jdesktop.swingx.painter.ImagePainter();
        jXPanel1 = new org.jdesktop.swingx.JXPanel();
        panelCentral = new org.jdesktop.swingx.JXPanel();
        textPaneDescription = new javax.swing.JTextPane();
        textPaneAuthor = new javax.swing.JTextPane();
        lbApplicationName = new javax.swing.JLabel();
        lbApplicationVersion = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbLogo = new javax.swing.JLabel();
        btFermer = new javax.swing.JButton();

        imagePainterLogo.setPaintStretched(true);

        setTitle("A propos");
        setBackground(new java.awt.Color(51, 51, 51));
        setBounds(new java.awt.Rectangle(50, 50, 440, 360));
        setCancelButton(btFermer);
        setDefaultButton(btFermer);
        setResizable(false);

        jXPanel1.setBackground(new java.awt.Color(102, 102, 102));

        panelCentral.setBackground(new java.awt.Color(0, 0, 0));
        panelCentral.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        textPaneDescription.setEditable(false);
        textPaneDescription.setFont(new java.awt.Font("Tahoma", 2, 11));
        textPaneDescription.setForeground(new java.awt.Color(153, 153, 255));
        textPaneDescription.setText("Description :");
        textPaneDescription.setOpaque(false);

        textPaneAuthor.setBorder(null);
        textPaneAuthor.setEditable(false);
        textPaneAuthor.setFont(new java.awt.Font("Tahoma", 2, 11));
        textPaneAuthor.setForeground(new java.awt.Color(255, 255, 255));
        textPaneAuthor.setText("auteurs");
        textPaneAuthor.setOpaque(false);

        lbApplicationName.setFont(new java.awt.Font("Tahoma", 1, 20));
        lbApplicationName.setForeground(new java.awt.Color(255, 255, 255));
        lbApplicationName.setText("nomApplication");

        lbApplicationVersion.setFont(new java.awt.Font("Tahoma", 3, 12));
        lbApplicationVersion.setForeground(new java.awt.Color(255, 255, 255));
        lbApplicationVersion.setText("version");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Auteurs :");

        lbLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panelCentralLayout = new javax.swing.GroupLayout(panelCentral);
        panelCentral.setLayout(panelCentralLayout);
        panelCentralLayout.setHorizontalGroup(
            panelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCentralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCentralLayout.createSequentialGroup()
                        .addComponent(lbLogo, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textPaneDescription, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                            .addComponent(lbApplicationName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbApplicationVersion, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(124, 124, 124))
                    .addGroup(panelCentralLayout.createSequentialGroup()
                        .addGroup(panelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelCentralLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(textPaneAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4))
                        .addContainerGap(31, Short.MAX_VALUE))))
        );
        panelCentralLayout.setVerticalGroup(
            panelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCentralLayout.createSequentialGroup()
                .addGroup(panelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelCentralLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(lbApplicationName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbApplicationVersion)
                        .addGap(18, 18, 18)
                        .addComponent(textPaneDescription))
                    .addComponent(lbLogo, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textPaneAuthor, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                .addContainerGap())
        );

        btFermer.setBackground(new java.awt.Color(51, 51, 51));
        btFermer.setFont(new java.awt.Font("Tahoma", 1, 11));
        btFermer.setForeground(new java.awt.Color(255, 255, 255));
        btFermer.setText("Fermer");
        btFermer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFermerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jXPanel1Layout = new javax.swing.GroupLayout(jXPanel1);
        jXPanel1.setLayout(jXPanel1Layout);
        jXPanel1Layout.setHorizontalGroup(
            jXPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXPanel1Layout.createSequentialGroup()
                .addGroup(jXPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jXPanel1Layout.createSequentialGroup()
                        .addGap(289, 289, 289)
                        .addComponent(btFermer, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jXPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelCentral, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jXPanel1Layout.setVerticalGroup(
            jXPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelCentral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btFermer)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jXPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jXPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btFermerActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btFermerActionPerformed
    {//GEN-HEADEREND:event_btFermerActionPerformed
        //this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btFermerActionPerformed
    
    public JLabel getApplicationNameLabel()
    {
        return this.lbApplicationName;
    }
    
    public JLabel getApplicationVersionLabel()
    {
        return this.lbApplicationVersion;
    }
    
    public JTextPane getAuthorTextPane()
    {
        return this.textPaneAuthor;
    }
    
    public JLabel getLogoLabel()
    {
        return this.lbLogo;
    }
    
    public JTextPane getDescriptionTextPane()
    {
        return this.textPaneDescription;
    }
    
    public static void main(String[] argv)
    {
        FenetreAPropos f = new FenetreAPropos("Mon Application", "0.9", 
            "Descriction :\nBlabla", "liste des auteurs");
        f.setVisible(true);
        
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btFermer;
    private org.jdesktop.swingx.painter.ImagePainter imagePainterLogo;
    private javax.swing.JLabel jLabel4;
    private org.jdesktop.swingx.JXPanel jXPanel1;
    private javax.swing.JLabel lbApplicationName;
    private javax.swing.JLabel lbApplicationVersion;
    private javax.swing.JLabel lbLogo;
    private org.jdesktop.swingx.JXPanel panelCentral;
    private javax.swing.JTextPane textPaneAuthor;
    private javax.swing.JTextPane textPaneDescription;
    // End of variables declaration//GEN-END:variables
    
}
